apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: docker.io/devopsteam303/march_nodejs:v4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: LoadBalancer ##load balancer
metadata:
  name: nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
  - port: 80
    targetPort: 80
